---
- name: CCLS | Install ccls | nix
  lineinfile:
    path: "{{ nix_config }}"
    insertbefore: ".* Language Servers End .*"
    line: "ccls"

- name: CCLS | Configure ccls for Neovim | nix
  changed_when: false
  blockinfile:
    path: "{{ nvim_coc_settings_file }}"
    marker: "// !-- {mark} CCLS Language Server Config --"
    insertbefore: ".*LSP Provider\\(End\\).*"
    block: |
      "ccls": {
        "command": "{{ nix_bin }}/ccls",
        "filetypes": ["c", "cc", "cpp", "cxx", "c++", "objc", "objcpp"],
        "rootPatterns": [".ccls", "compile_commands.json", ".git/", ".vscode"],
        "initializationOptions": {
          "cache": {
            "directory": "{{ ccls_tmp_dir }}"
          },
          // clang args(begin)
          // clang args(end)
        }
      },
