---
- name: CCLS | Install ccls | task
  import_tasks: install_ccls.yml

- name: CMake | Install cmake | task
  import_tasks: install_cmake.yml

- name: Ninja | Install ninja | task
  import_tasks: install_ninja.yml

- name: VSCode CppTools | Install VSCode CppTools | task
  import_tasks: install_vscode_cpptools.yml

- name: Nix | Build Nix Environment | nix
  changed_when: false
  command:
    cmd: "{{ nix_bin }}/nix-env -i {{ nix_buildenv_name }}"

