---
#- name: CCLS | Install ccls | task
#  import_tasks: install_ccls.yml
#
#- name: Clangd | Install Clangd | task
#  import_tasks: install_clangd.yml

- name: Boost | Install boost | task
  import_tasks: install_boost.yml

#- name: CMake | Install cmake | task
#  import_tasks: install_cmake.yml
#
#- name: Ninja | Install ninja | task
#  import_tasks: install_ninja.yml

- name: VSCode CppTools | Install VSCode CppTools | task
  import_tasks: install_vscode_cpptools.yml

- name: Neovim | Install Neovim Plugin/Settings | task
  import_tasks: install_neovim_plugins.yml

#- name: Nix | Build Nix Environment | nix
#  changed_when: false
#  command:
#    cmd: "{{ nix_bin }}/nix-env -i {{ nix_buildenv_name }}"
