---
#- name: CCLS | Install ccls | task
#  import_tasks: install_ccls.yml
#
#- name: Clangd | Install Clangd | task
#  import_tasks: install_clangd.yml

- name: Boost | Install CppTools | task
  import_tasks: install_cpp_tools.yml

#- name: CMake | Install cmake | task
#  import_tasks: install_cmake.yml
#
#- name: Ninja | Install ninja | task
#  import_tasks: install_ninja.yml

- name: VSCode CppTools | Install VSCode CppTools | task
  import_tasks: install_vscode_cpptools.yml

#- name: Neovim | Install Neovim Plugin/Settings | task
#  import_tasks: install_neovim_plugins.yml

#- name: GCCDiag | Install GCCDiag | task
#  import_tasks: install_gccdiag.yml
